name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Expose GIT Commit Data
        uses: rlespinasse/git-commit-data-action@v1.x

      - id: version
        run: |
          echo "$(echo ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} | sed -r 's/Release //')"

      - id: tag
        run: |
          echo "$(echo ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} | sed -r 's/Release /v/')"

      - run: echo "${{ steps.version.output }}"
      - run: echo "${{ steps.tag.output }}"

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.version.output }}
          message: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}
          token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      is_release: ${{ startsWith(env.GIT_COMMIT_MESSAGE_SUBJECT, 'Release') }}
      version: ${{ steps.version.output }}
      tag: ${{ steps.tag.output }}
      commit_message: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ success() && needs.check.outputs.is_release == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package Application
        if: ${{ startsWith(env.GIT_COMMIT_MESSAGE_SUBJECT, 'Release') }}
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: src

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.check.outputs.version }}
          tag_name: ${{ needs.check.outputs.tag }}
          draft: false
          prerelease: false
          files: src/dist/linux/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      url: ${{ steps.release.outputs.upload_url }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [check, build]

    steps:
      - name: Notify the Author(s)
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Release Notification
          SLACK_AVATAR: sender
        with:
          args: "[${{ github.repository }}] Published the release [${{ needs.check.version }}] available\n${{ needs.build.url }}\n${{ needs.build.upload_url }}"
