name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Expose GIT Commit Data
        uses: rlespinasse/git-commit-data-action@v1.x

    outputs:
      is_release: ${{ startsWith(env.GIT_COMMIT_MESSAGE_SUBJECT, 'Release') }}
      version: echo "$(echo ${{ needs.tests.outputs.commit_message }} | sed -r 's/Release //')"
      tag: echo "$(echo ${{ needs.tests.outputs.commit_message }} | sed -r 's/Release /v/')"
      commit_message: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ success() && needs.check.outputs.is_release == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package Application
        if: ${{ startsWith(env.GIT_COMMIT_MESSAGE_SUBJECT, 'Release') }}
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: src

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.check.outputs.version }}
          tag_name: ${{ needs.check.outputs.tag }}
          draft: false
          prerelease: false
          files: src/dist/linux/scale
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [check, build]

    steps:
      - name: Notify the Author(s)
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Release Notification
          SLACK_AVATAR: sender
        with:
          args: "[${{ github.repository }}] Published the release [${{ needs.check.version }}]"
